  - name: download deb
    command: curl -L -O artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-7.6.2-amd64.deb
 
  - name: install deb
    command: dpkg -i auditbeat-7.6.2-amd64.deb

  - name: drop in configuration file 
    copy:
      src: auditbeat.yml
      dest: /etc/auditbeat/auditbeat.yml


  - name: setup
    command: auditbeat setup

  - name: start service
    command: service auditbeat start

