  - name: download deb 
    command: curl -L -O artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: install deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: drop in config file 
    copy:
      src: filebeat.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure system module
    command: filebeat modules enable system

  - name: setup
    command: filebeat setup

  - name: start service
    command: service filebeat start

