  - name: download deb
    command: curl -L -O artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.2-amd64.deb
 
  - name: install deb
    command: dpkg -i metricbeat-7.6.2-amd64.deb

  - name: drop in configuration file 
    copy:
      src: metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: metricbeat modules enable docker

  - name: setup
    command: metricbeat setup

  - name: start service
    command: service metricbeat start
